name: Zones

on:
  # schedule:
  #   - cron: '0 2 * * *'
  workflow_dispatch:
  
jobs:
  fetch_zones:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get all Cloudflare Zones
      run: |
        curl -X GET "https://api.cloudflare.com/client/v4/zones" \
             -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
             -H "Content-Type: application/json" | jq '.result[] | .name' > zones.json
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    - name: Commit and push if it's updated
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-action@github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated zones.json on ${timestamp}" || exit 0
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
